config:
  requests:
    enable_expiration: true
    expire_time: 60
  gender:
    enable_other: true
  storage:
    method: YAML
    mongodb:
      hostname: 127.0.0.1
      port: 27017
      username: ""
      password: ""
      database: "marriagelab"
      ssl: false